import { icons } from "../constants";

const randomIncomeTypeGenerator = () => {
  const incomeTypes = ["income", "expense"];
  return incomeTypes[Math.floor(Math.random() * incomeTypes.length)];
};
export const DUMMY_PAY = [
  {
    id: 1,
    date: "2024-10-1",
    name: "John Doe",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 2,
    date: "2024-10-1",
    name: "Jane Smith",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 3,
    date: "2024-10-1",
    name: "Alice Johnson",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 4,
    date: "2024-10-1",
    name: "Bob Brown",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 5,
    date: "2024-10-1",
    name: "Charlie Davis",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 6,
    date: "2024-10-1",
    name: "Diana Green",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 7,
    date: "2024-10-1",
    name: "Ethan White",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 8,
    date: "2024-10-1",
    name: "Fiona Black",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 9,
    date: "2024-10-1",
    name: "George Blue",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 10,
    date: "2024-10-1",
    name: "Hannah Red",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 11,
    date: "2024-10-1",
    name: "Ian Yellow",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 12,
    date: "2024-10-1",
    name: "Julia Pink",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 13,
    date: "2024-10-1",
    name: "Kevin Purple",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 14,
    date: "2024-10-1",
    name: "Laura Orange",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  {
    id: 15,
    date: "2024-10-1",
    name: "Michael Grey",
    image: icons.userDefault2,
    money: "$00",
    incomeType: randomIncomeTypeGenerator(),
    time: "4:24PM",
  },
  // Add more users here if needed...
];
